// This file is auto-generated. DO NOT EDIT BY HAND
#pragma once

#include "tr_local.h"

extern const GPUProgramDesc fallback_bokehProgram;
extern const GPUProgramDesc fallback_calclevels4xProgram;
extern const GPUProgramDesc fallback_depthblurProgram;
extern const GPUProgramDesc fallback_dglow_downsampleProgram;
extern const GPUProgramDesc fallback_dglow_upsampleProgram;
extern const GPUProgramDesc fallback_down4xProgram;
extern const GPUProgramDesc fallback_fogpassProgram;
extern const GPUProgramDesc fallback_gaussian_blurProgram;
extern const GPUProgramDesc fallback_genericProgram;
extern const GPUProgramDesc fallback_highpassProgram;
extern const GPUProgramDesc fallback_lightallProgram;
extern const GPUProgramDesc fallback_prefilterEnvMapProgram;
extern const GPUProgramDesc fallback_pshadowProgram;
extern const GPUProgramDesc fallback_refractionProgram;
extern const GPUProgramDesc fallback_shadowvolumeProgram;
extern const GPUProgramDesc fallback_smaaBlendWeightProgram;
extern const GPUProgramDesc fallback_smaaEdgeProgram;
extern const GPUProgramDesc fallback_smaaResolveProgram;
extern const GPUProgramDesc fallback_smaaTemporalResolveProgram;
extern const GPUProgramDesc fallback_ssaoProgram;
extern const GPUProgramDesc fallback_surface_spritesProgram;
extern const GPUProgramDesc fallback_texturecolorProgram;
extern const GPUProgramDesc fallback_tonemapProgram;
extern const GPUProgramDesc fallback_velocityProgram;
extern const GPUProgramDesc fallback_weatherProgram;
extern const GPUProgramDesc fallback_weatherUpdateProgram;
